### ISSUE TITLE
Mini-batch Regularization

### ISSUE THREAD

**Issue by voladorlu** [zhougr1993/DeepInterestNetwork#10]
Hi, Guorui, May I ask which part of the code that exactly implements the parameter regularization? It seems a missing part when initializing the computation model in the __init__() function of din.py file. Waiting for your response. -:)

**Comment by zhougr1993** [comment]
Statistics of public data is much more less than the real data in our advertising system. And Mini-batch Regularization is only applied in industrial data and real world system.

**Comment by voladorlu** [comment]
@zhougr1993 Hi, Guorui, Thanks for your response. May I ask the impact of mini-batch regularization on the performance when running your code in public data like Amazon reviews. Is it save to regard this implementation as a strong baseline with the model regularization?

**Comment by zhougr1993** [comment]
> @zhougr1993 Hi, Guorui, Thanks for your response. May I ask the impact of mini-batch regularization on the performance when running your code in public data like Amazon reviews. Is it save to regard this implementation as a strong baseline with the model regularization?

All experiments on Amazon reviews is conducted with out mini-batch regularization. We only evaluate the effectiveness of MBA-Reg on industrial data.

**Comment by voladorlu** [comment]
@zhougr1993  Thank you for your reply. I got it.
