### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alvykhodtseva** [zhougr1993/DeepInterestNetwork#12]
Hello! I'm running on Windows 10 and get the following error in din/log.txt:

[None, 128]
[None, 128]
[None, 128]
[None, 100, 128]
[None, 2]
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    print('test_gauc: %.4f\t test_auc: %.4f' % _eval(sess, model))
  File "train.py", line 75, in _eval
    for _, uij in DataInputTest(test_set, test_batch_size):
TypeError: iter() returned non-iterator of type 'DataInputTest'

Is there a way to fix it? 
Thanks in advance!

**Comment by nanffiy** [comment]
please refer first question [TypeError: iter() returned non-iterator of type 'DataInput' ]()

**Comment by AzizIlyosov** [comment]
You have  use  python 3  pls  try  with python 2.7

**Comment by Ken-Con** [comment]
you can change next with __next__ to fixed it
