### ISSUE TITLE
about DeepFM model

### ISSUE THREAD

**Issue by Ken-Con** [zhougr1993/DeepInterestNetwork#13]
Hello, nice work! I have some doubts about your DeepFM model.
1、why do you concat u_emb[0]  i_emb[0] in d_layer_fm_i node?
2、I didnt see linear part in fm part.
3、In predict phrase, self.score_i is obtained by add bias and dnn part without fm part. This really made me confused.
Thanks!

**Comment by zhougr1993** [comment]
Actually we use u_emb[0] and i _emb[0] as the linear part of these two feature.
problem 3 is an issue in this code. I will report results of exps on deepFM in correct code.

**Comment by Ken-Con** [comment]
> Actually we use u_emb[0] and i _emb[0] as the linear part of these two feature.
> problem 3 is an issue in this code. I will report results of exps on deepFM in correct code.

thanks!

**Comment by zhougr1993** [comment]
> > Actually we use u_emb[0] and i _emb[0] as the linear part of these two feature.
> > problem 3 is an issue in this code. I will report results of exps on deepFM in correct code.
> 
> thanks!
Thanks for your comment.
We report new results of deepFM via README.md in deepFM files.
New exp results of deepFM for Amazon(Electro) is AUC: 0.86952 while we report 0.8683 in our paper.
