### ISSUE TITLE
hi, can you share your python script about movieLens?

### ISSUE THREAD

**Issue by ailanchong** [zhougr1993/DeepInterestNetwork#14]
Hi, i'm doing some experiments about ctr. To compare with your din carefully, i want to use the same ways about dealing with the movieLens. 
Thanks.
my email is 13241818007@163.com

**Comment by zhougr1993** [comment]
Sorry, I can not provide python implement of movielens. Stats of MovieLens is much larger than Amazon data. Thus experiments on movieLens are conducted via XDL，which is an industrial deep learning system of Alibaba. 
Most of my internships in Alibaba are developing XDL. And the exciting thing is that XDL is going to be open source in few weeks.

**Comment by ailanchong** [comment]
thx, I have read your another paper DIEN, and use the same two subsets of  Amazon to do my experiments.
Thanks for your work.
