### ISSUE TITLE
about wide_deep model

### ISSUE THREAD

**Issue by wuqingzhou828** [zhougr1993/DeepInterestNetwork#15]
hello,mr.zhou:
# wide part
        d_layer_wide_i = tf.concat([tf.gather(u_emb, [0], axis=-1) * tf.gather(i_emb, [0], axis=-1),
                                    tf.gather(u_emb, [-1], axis=-1) * tf.gather(i_emb, [-1], axis=-1),
                                    tf.gather(u_emb, [hidden_units // 2], axis=-1) * tf.gather(i_emb,
                                                                                               [hidden_units // 2],
                                                                                               axis=-1)], axis=-1)

error: InvalidArgumentError (see above for traceback): indices[0] = -1 is not in [0, 128)
when i change -1 to 1 , it can run. 
why ?

**Comment by DoubleYing** [comment]
嗯，据我理解，Wide&Deep的wide部分，是人工构建的特征，所以concat中的这几个是随机选择的几个交叉项，还是有特殊含义的呢？

**Comment by Lw-Cui** [comment]
`gather` 函数的具体实现 `def gather_v2(params, indices, axis, name=None)` 中提到 `indices` 在 GPU 和 CPU 上的不同表现：

```
  Note that on CPU, if an out of bound index is found, an error is returned.

  On GPU, if an out of bound index is found, a 0 is stored in the

  corresponding output value.
```

所以如果在 CPU 机器上跑需要改动程序。
