### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by Ken-Con** [zhougr1993/DeepInterestNetwork#17]
Hi, I have some problems about your code.
1. In your code, the prelu and dice parameters doesn't share between i_emb and j_emb. That means the parameters in j_emb code cannot get any training. 
2. about auc calculation, you concat [i_emb,hist] and [j_emb, hist]. But we get the hist from attention between i_emb and h_emb. This is equivalent to give the model a prior information that the hist is closer to i_emb than j_emb.

**Comment by zhougr1993** [comment]
Thanks for your comments.
question 1: parameter of dice and prelu is set as "reuse=True".
question 2: This is a big issue and will make impact on results of exps. I will fix this issue and report the new results in ReadMe. Based on our practice on the real system and exps of new paper DIEN： https://github.com/mouna99?tab=repositories, effectiveness of DIN is confirmed.

**Comment by zhougr1993** [comment]
> @zhougr1993 thanks, but In this code "reuse=True" is not used.
Thanks.
The last commit "fix parameters of dice and prelu" has fixed this problem and the new results can be found in DeepInterestNetwork/din/log_din_dice. Although the log is not completed for limited time, AUC of din+dice has reached 0.8926 higher than 0.8818 reported in our paper.
