### ISSUE TITLE
Din代码和论文不一致问题

### ISSUE THREAD

**Issue by caojiajia** [zhougr1993/DeepInterestNetwork#18]
@zhougr1993 
请教一下，看了din那篇论文里，发现其中activation unit的实现和这里有几点不一样
1. 论文里的小网络输入是out product，这里是inner product。
2. 论文里激活函数是prelu，这里是sigmoid。
3. 论文里接受不用softmax归一化，这里用了归一化。
不知道哪种效果比较好一些，为什么做了修改。

**Comment by zhougr1993** [comment]
1. 其实准确的描述应该是 element wise mult. 但是在PNN开始 就用out product描述这种OP我们就沿用了，code里绝对不是inner product.
2. code里的Dice.py里面有PReLU的实现完全可以自己做相关的实验。
3. softmax的归一化也有选项是否打开，所有人都可以试验是否需要归一化。

code里给了很多选项，并没有为效果优劣考虑而是可以支持大家的尝试，并没有为了效果做修改的考量。

**Comment by caojiajia** [comment]
感谢你的回答！第一个问题是我描述有误，不是inner product。
