### ISSUE TITLE
What is the reference to the way you calculate AUC?

### ISSUE THREAD

**Issue by StKlaas** [zhougr1993/DeepInterestNetwork#2]
Hi,

I do not understand the codes on computing AUC score? https://github.com/zhougr1993/DeepInterestNetwork/blob/master/base_model/train.py#L26
Are there any references? Thanks in advance.

**Comment by zhougr1993** [comment]
Hi,

You can get some idea from https://stats.stackexchange.com/questions/105501/understanding-roc-curve/105577.
The codes of 'line 26 in train.py' are also following the same idea.

**Comment by StKlaas** [comment]
@zhougr1993 Thanks a lot. When we sort the scores from high to low,  the AUC become auc / (2.0 * tp2 * fp2)) in your computation, is that right?

**Comment by zhougr1993** [comment]
Yes. (1 / 2.0) means calculate the area of each trapezoid.
