### ISSUE TITLE
wide&deep中tf.gather  u_emb,i_emb的第一列/中间一列/最后一列的含义

### ISSUE THREAD

**Issue by kejunxiao** [zhougr1993/DeepInterestNetwork#20]
对这段代码有些迷惑。wide部分的实现难道不是一个dim=(n_user + n_item + n_cate + n_other_cross_fetures)的长向量乘一个相同维度的multi-hot向量吗？为什么代码中是 tf.gather(u_emb,i_emb的第一列/中间一列/最后一列) 然后再加一个全连接层呢？

**Comment by zhougr1993** [comment]
这里就是用最它们各自的最后一维来模拟wide部分，因为这个数据集里没有作cross的feature。其实wide部分 emmm没什么用 如果有cross feature放进deep部分是一样的。

**Comment by kejunxiao** [comment]
get了，所以deepfm的一阶特征也是用一样的方法去模拟咯？
