### ISSUE TITLE
对attention方法体的一点点疑惑

### ISSUE THREAD

**Issue by LuGuangWang** [zhougr1993/DeepInterestNetwork#23]
attention方法体中的din_all = tf.concat([queries, keys, queries-keys, queries*keys], axis=-1)。为什么要这样扩展？ queries-keys还可以理解为：当前行为与历史行为的差距 ，可queries*keys是为了什么呢？ 还望大神解惑

**Comment by zhougr1993** [comment]
这是个小细节，其实很多算法都有各种解释，比如这个差我们可以解释为差距，这个乘积我们可以解释为高阶信息。

但是真正背后的思考是，在线系统的latency是要求很严格的，而attention部分的计算是发生在target item和user的behavior list之间的，同时在线打分的时候每次要计算几百个target item的CTR。这使得attention部分的计算复杂度增加一点，在线的计算压力就会增加非常多，所以attention unit必须设计得足够简单。如果这个地方没什么限制显然把attention unit的神经网络加深就好了，但是有限制，我们希望计算简单效果又好，就凭经验加了一个差和一个乘积，用先验的知识降低模型拟合的难度，在线实验验证也有效就在公开数据集也加上了。

希望对你有帮助

**Comment by DannyWu1996** [comment]
你好，我顺便提问一个问题在attention方法体中，因为针对每个用户的hist长度不同，所以最初取得是batch中最长的hist来构成[B, T]维的矩阵，于是对于一个用户u其hist长度不够T的时候，会构成一条(h1, h2, h3,... 0. 0. 0)的向量作为其历史行为，但是这里的0最终会取到第0号商品的emb
所以在attention过程中说有一个paddings = tf.one_like(outputs) *(-2 ** 32 +1 )这里不太理解。希望大神解惑，我私以为paddings = tf.zeros_like(outputs)会更合理些，若是为了符合outputs=tf.where(key_masks, outputs, paddings)这个选择的情况的话

**Comment by LuGuangWang** [comment]
非常感谢，我懂您的意思了

**Comment by sudongxiang** [comment]
这个乘积可以理解为：“方向”，例如向量（-1.0，1.0，1.0）和（1.0，0.2，0.1），以及（-1.0，1.0，1.0）和（-1.0，0.2，0.1），第一组的乘积（-1，0.2，0.1）第二组乘积（1，0.2，0.1），可见第二组更为相似。why？因为正负相同！即“方向”相同，这也是信息~

**Comment by LuGuangWang** [comment]
这个解释可以的 厉害厉害
