### ISSUE TITLE
劳驾~关于 attention 的激活函数sigmoid

### ISSUE THREAD

**Issue by sudongxiang** [zhougr1993/DeepInterestNetwork#27]
在din/model.py代码中attention里面使用了sigmoid作为激活函数，我们常见的是relu，这里的sigmoid有何特殊之处，对照过效果吗？

**Comment by zhougr1993** [comment]
> 在din/model.py代码中attention里面使用了sigmoid作为激活函数，我们常见的是relu，这里的sigmoid有何特殊之处，对照过效果吗？

没有什么特殊之处，只是给个例子，具体用什么激活函数不同的情景结论应该也不一样，但是据经验一般prelu和我们提出的dice会好于 sigmoid和relu
