### ISSUE TITLE
好像混用了python2的代码

### ISSUE THREAD

**Issue by thedogb** [zhougr1993/DeepInterestNetwork#4]
在din/input.py 中用的是next(), 在din/model.py里用的是print 没加括号。但是readme里写的是python>=3.6.3。这是有某种python3兼容python2的方法，还是单纯混用了python2的代码？

抱歉，我是新手，如果提问有问题，还请见谅！

**Comment by zhougr1993** [comment]
我的疏忽，python 2.7应该是能运行这个代码的 Readme里有点错误

**Comment by thedogb** [comment]
非常感谢您的回答
