### ISSUE TITLE
关于GAUC的计算

### ISSUE THREAD

**Issue by patricxu** [zhougr1993/DeepInterestNetwork#42]
为啥gauc是这个
    x = i_b - j_b + d_layer_3_i - d_layer_3_j 
的平均值呢？

其中 x = 正样本的logits - 负样本的logits

**Comment by zhougr1993** [comment]
因为，在这个case里 一个user只有两条样本 正样本和我们负采样的负样本，所以一个user的auc就和acc差不多了

**Comment by patricxu** [comment]
谢谢
