### ISSUE TITLE
Questions about Wide and deep model

### ISSUE THREAD

**Issue by czisok** [zhougr1993/DeepInterestNetwork#45]
After reading your paper, I have a few questions about wide & deep model,wish to communicate wiht you.
`# wide part
    d_layer_wide_i = tf.concat([tf.gather(u_emb, [0], axis=-1) * tf.gather(i_emb, [0], axis=-1),
                                tf.gather(u_emb, [-1], axis=-1) * tf.gather(i_emb, [-1], axis=-1),
                                tf.gather(u_emb, [hidden_units // 2], axis=-1) * tf.gather(i_emb, [hidden_units // 2], axis=-1)],
                               axis=-1)`
1. Is this place counting cross features?
2. In the original paper, didn't it say to make cross features of discrete features?
3. Why select [0],[-1] [hiddens // 2]?

**Comment by zhougr1993** [comment]
> After reading your paper, I have a few questions about wide & deep model,wish to communicate wiht you.
> `# wide part d_layer_wide_i = tf.concat([tf.gather(u_emb, [0], axis=-1) * tf.gather(i_emb, [0], axis=-1), tf.gather(u_emb, [-1], axis=-1) * tf.gather(i_emb, [-1], axis=-1), tf.gather(u_emb, [hidden_units // 2], axis=-1) * tf.gather(i_emb, [hidden_units // 2], axis=-1)], axis=-1)`
> 
> 1. Is this place counting cross features?
> 2. In the original paper, didn't it say to make cross features of discrete features?
> 3. Why select [0],[-1] [hiddens // 2]?

1. yes
2, 3. In amazon data, there are only two kind of feature category and item. Thus, we select [0],[-1] to mimic the feature crossing in our paper. Actually, wide part makes little difference.
