### ISSUE TITLE
TypeError: iter() returned non-iterator of type 'DataInput'

### ISSUE THREAD

**Issue by shifengren** [zhougr1993/DeepInterestNetwork#5]
When I run program according to your instruction, I get such error message. The Python version is 3.65. The iteration protocol in python 3.65 has been changed to __next__ method rather than  next() method. Hope to make this program be better

**Comment by AzizIlyosov** [comment]
Yes  I also  had  same error 

> When I run program according to your instruction, I get such error message. The Python version is 3.65. The iteration protocol in python 3.65 has been changed to **next** method rather than next() method. Hope to make this program be better

Yes I had  also has  such  error  and  when I changed  "**next**" keyword  to  **__next__** it is  run  without  problem
