### ISSUE TITLE
关于attention的实现

### ISSUE THREAD

**Issue by ZhengYukai666** [zhougr1993/DeepInterestNetwork#50]
问题1:论文中attention里有一个out product是叉乘/外积的意思吗？

问题2:代码中的实现方法是tf.concat([queries, keys, queries-keys, queries*keys], axis=-1)
但是论文中是将queries, keys, out product(queries, keys)这三个东西concat起来，为什么代码和论文不一致呢？

**Comment by ZhangYuef** [comment]
同这里有疑问 [link](https://github.com/zhougr1993/DeepInterestNetwork/blob/634310ac2c31903d2786af31cec0a5900d343d74/din/model_dice.py#L204)

```python
  din_all = tf.concat([queries, keys, queries-keys, queries*keys], axis=-1)
```
希望能详细解答一下～

**Comment by ZhangYuef** [comment]
> 问题1:论文中attention里有一个out product是叉乘/外积的意思吗？
> 
> 问题2:代码中的实现方法是tf.concat([queries, keys, queries-keys, queries*keys], axis=-1)
> 但是论文中是将queries, keys, out product(queries, keys)这三个东西concat起来，为什么代码和论文不一致呢？

ISSUE #8  #23  对这个问题有所解答，可参考～
