### ISSUE TITLE
关于DIN复现的结果问题

### ISSUE THREAD

**Issue by hit-joseph** [zhougr1993/DeepInterestNetwork#57]
你好，用你给的实验数据跑DIN部分的实验获取到的结果和论文上面的结果相差2个点左右，请问参数配置有需要改动的地方吗，不知道该怎么去分析了？请赐教

**Comment by xiyue-yi** [comment]
您好，我在复现时候也遇到了类似问题，因为算力限制din只跑到了第4个epoch，gauc到了0.776左右，但是根据作者公布的训练过程到这里gauc应该已经到了0.85-0.86左右，参数用的是代码指定的，和论文里给出的好像是一致的，想问一下您后来解决了这个复现不一致的问题吗

**Comment by hit-joseph** [comment]
您好，您的邮件我已收到，我会尽快拜读O(∩_∩)O~！！！颜欣哈尔滨工业大学计算机学院
