### ISSUE TITLE
Embedding of user (named after `u_emb`) seem to be unused in DIN model

### ISSUE THREAD

**Issue by shifengren** [zhougr1993/DeepInterestNetwork#6]
![image](https://user-images.githubusercontent.com/13633999/46139192-70456a80-c280-11e8-862d-33a8fe17c538.png)
![image](https://user-images.githubusercontent.com/13633999/46139208-7f2c1d00-c280-11e8-99d4-89ae80bc7bb6.png)
![image](https://user-images.githubusercontent.com/13633999/46139221-8c490c00-c280-11e8-8c7f-7a5626732c91.png)

Both variable `i_emb` and `h_emb`  are irrelevant to embedding vector `u_emb`, while `u_emb` is assigned to `hist` (attention result).  It's strange to define user embedding vector without using it.

I would appreciate it if you explain it in detail. Thanks

**Comment by zhougr1993** [comment]
We did not use the u_emb in this paper. Only 'hist' of users are used to represent users.
https://github.com/zhougr1993/DeepInterestNetwork/issues/3
