### ISSUE TITLE
Mini-batch Aware Regularization正则化在代码哪里体现了呀。各位大佬

### ISSUE THREAD

**Issue by cuiweizuishuai** [zhougr1993/DeepInterestNetwork#60]

**Comment by zhougr1993** [comment]
这部分是在面对ID比较多的情况下才需要做的工作，公开的数据集体量都比较小，做MBA reg也没有特别大意义，就没有给这方面的实现。这部分的工作实现其实原理很简单，论文里应该已经讲得比较清楚了，具体实现的话需要放到embedding 更新的逻辑里面了。
