### ISSUE TITLE
代码的命名格式太差

### ISSUE THREAD

**Issue by wind-meta** [zhougr1993/DeepInterestNetwork#61]
是经过代码混淆后特意做的吗？

**Comment by yichudu** [comment]
> 是经过代码混淆后特意做的吗？

又不是js,不会主动混淆的...  
作者编码习惯吧, 可读性不强

**Comment by zhougr1993** [comment]
这份code确实质量不高。从DIEN开始我们就重构了code，如果觉得这份代码不方便迭代的话可以用DIEN和MIMN的
https://www.aaai.org/ojs/index.php/AAAI/article/download/4545/4423
https://arxiv.org/pdf/1905.09248
