### ISSUE TITLE
代码写的太差了，p8大佬

### ISSUE THREAD

**Issue by weiyu322** [zhougr1993/DeepInterestNetwork#67]
作为阿里算法的门面，这个开源代码质量真的挺失望

**Comment by zhougr1993** [comment]
嗯，这份code确实质量不高。从DIEN开始我们就重构了code，如果觉得这份代码不方便迭代的话可以用DIEN和MIMN的
https://www.aaai.org/ojs/index.php/AAAI/article/download/4545/4423
https://arxiv.org/pdf/1905.09248
