### ISSUE TITLE
Different AUC implementation with the paper

### ISSUE THREAD

**Issue by liuhu-bigeye** [zhougr1993/DeepInterestNetwork#71]
In the paper, 'AUC' is defined as: <img src="https://render.githubusercontent.com/render/math?math=AUC=\frac{\sum_{i=1}^{n} impression_i \times AUC_i}{\sum_{i=1}^{n} impression_i}">.

However, the two metrics provided in the code are: <img src="https://render.githubusercontent.com/render/math?math=GAUC=\frac{\sum_{i=1}^{n}AUC_i}{n}"> and <img src="https://render.githubusercontent.com/render/math?math=AUC_{all}">.

Please correct me if I misunderstand the [code](https://github.com/zhougr1993/DeepInterestNetwork/blob/master/din/train.py#L72).

**Comment by liuhu-bigeye** [comment]
Reimplementation with the metric in the paper result in a lot higher score, Amazon Electro: 0.9776.
So I guess the AUC defined in the paper is not correct and other works should not use this metric to make fair comparison with the paper.

**Comment by PengDanni** [comment]
> In the paper, 'AUC' is defined as: ![](https://render.githubusercontent.com/render/math?math=AUC=\frac{\sum_{i=1}^{n} impression_i \times AUC_i}{\sum_{i=1}^{n} impression_i}).
> 
> However, the two metrics provided in the code are: ![](https://render.githubusercontent.com/render/math?math=GAUC=\frac{\sum_{i=1}^{n}AUC_i}{n}) and ![](https://render.githubusercontent.com/render/math?math=AUC_{all}).
> 
> Please correct me if I misunderstand the [code](https://github.com/zhougr1993/DeepInterestNetwork/blob/master/din/train.py#L72).

because in their test set, each user only has one positive sample and negative sample, the number of impressions for each user in the test set are the same, hence gauc == average auc

**Comment by PengDanni** [comment]
> Reimplementation with the metric in the paper results in a lot higher score, e.g. Amazon Electro: 0.9776.
> So I guess the AUC defined in the paper is not correct and other works should not use this metric to make fair comparison with the paper.

because in their test set, each user only has one positive sample and one negative sample, the number of impressions for each user in the test set are the same, hence gauc == average auc

**Comment by liuhu-bigeye** [comment]
Thanks for answering
