### ISSUE TITLE
原论文在介绍attention时候，叙述说放弃了softmax的归一化，但在代码中依旧保留了softmax，请问这是怎么回事？

### ISSUE THREAD

**Issue by lcwy220** [zhougr1993/DeepInterestNetwork#74]

**Comment by zhougr1993** [comment]
公开数据集的实现只是给一个demo，以及在公开数据集测试方法的效果。对于softmax这一段，公开数据集这个用户行为和数据的体量是体现不出来的。

**Comment by lcwy220** [comment]
> 公开数据集的实现只是给一个demo，以及在公开数据集测试方法的效果。对于softmax这一段，公开数据集这个用户行为和数据的体量是体现不出来的。

哦哦，这样啊，谢谢解释。
