### ISSUE TITLE
attention's issue ?

### ISSUE THREAD

**Issue by shifengren** [zhougr1993/DeepInterestNetwork#8]
Hi, zhou
In your original paper, local activation unit perform outer product between user's feature and AD's feature as following.
![image](https://user-images.githubusercontent.com/13633999/47412503-86bae500-d79e-11e8-8991-c608db008095.png)
In your public code rep, the `attention` function , if i'm right, is the implementation of `local activation unit`. However, I found that there are no outer product operation in this function. If i'm not right, please tell me what's the implementation of `local activate unit`, or could you explain the main idea of this implementation and what's the equivalent replacement to outer product mentioned in `local activation unit`. 
I'm looking forward to your reply. Thanks.

**Comment by zhougr1993** [comment]
Please check line 157 in DeepInterestNetwork/din/model.py. Out Product in our paper means element wise product. You can get more information from PNN [1].

[1] Qu Y. et al. 2016. Product-Based Neural Networks for User Response Prediction. In Proceedings of the 16th International Conference on Data Mining.
